import { Contact } from './contact';

export const CONTACTS:Contact[]=[
    {
        id:0,
        First_Name:"Nikhil",
        Last_Name:"Sharma",
        Email:"atnikhil95@gmail.com",
        PhoneNumber:7065175649,
        Status:"Inactive"
    },
    {
        id:1,
        First_Name:"Atul",
        Last_Name:"Sharma",
        Email:"atnikak@gmail.com",
        PhoneNumber:4585175649,
        Status:"Inactive"
    },
    {
        id:2,
        First_Name:"Chris",
        Last_Name:"Kumar",
        Email:"chriskumar@gmail.com",
        PhoneNumber:4598775649,
        Status:"Inactive"
    },
    {
        id:3,
        First_Name:"Steve",
        Last_Name:"Singh",
        Email:"stevesingh@gmail.com",
        PhoneNumber:7895775649,
        Status:"Inactive"
    },
    {
        id:4,
        First_Name:"Shawn",
        Last_Name:"Chaurasiya",
        Email:"shawnchaurasiya@gmail.com",
        PhoneNumber:7895775705,
        Status:"Inactive"
    },
    {
        id:5,
        First_Name:"Ben",
        Last_Name:"Chokes",
        Email:"benchokes@gmail.com",
        PhoneNumber:7895775705,
        Status:"Inactive"
    },
]